#define MAXIMO_MESA_ENTRADA 30
#define MAXIMO_COLAS_PARTICULARES 15
#define CANTIDAD_POLITICOS 45 //cantidad de politicos
#define CANTIDAD_EMPRESAS 45 //cantidad de empresarios
#define CANTIDAD_COMUNES 45  //cantidad de clientes comunes
#define ENTRADA 100
#define COLA_POLITICOS 101
#define POLITICO_ATENDIDO 102
#define ESPERANDO_POLITICO 103
#define COLA_EMPRESARIOS 104
#define ESPERANDO_EMPRESARIO 105
#define EMPRESARIO_ATENDIDO 106
#define COLA_CLIENTE_COMUN 107
#define COMUN_ESPERANDO 108
#define COMUN_ATENDIDO 109
#define DESPERTAR_EMPLEADO_COMUN 112
#define DESPERTAR_EMPLEADO_EMPRESA 113
#define MSGSIZE sizeof(char[1])
