#define MAXIMO_MESA_ENTRADA 30
#define MAXIMO_COLAS_PARTICULARES 15
#define CANTIDAD_POLITICOS 5 //cantidad de politicos
#define CANTIDAD_EMPRESAS 5 //cantidad de empresarios
#define CANTIDAD_COMUNES 5  //cantidad de clientes comunes
#define ENTRADA 100
#define COLA_POLITICOS 101  //PRESI_LLENO
#define POLITICO_ATENDIDO 102  //PRESI
#define ESPERANDO_POLITICO 103    //ESP_PRESI
#define COLA_EMPRESARIOS 104  //EMP_LLENO
#define ESPERANDO_EMPRESARIO 105  //ESP_EMP
#define EMPRESARIO_ATENDIDO 106  //EMP??
#define COLA_CLIENTE_COMUN 107  //COM_LLENO
#define COMUN_ESPERANDO 108  //ESP_COM
#define COMUN_ATENDIDO 109   //COM
#define DESPERTAR_EMPLEADO_COMUN 112 //DESPIERTO_COMUN
#define DESPERTAR_EMPLEADO_EMPRESA 113 //DESPIERTO_EMPRESA
#define MSGSIZE sizeof(char[1])
